# use this file to run the tests
# enter 'make' in the terminal to run the tests
all: run

run:
	
	@echo "Running Python scripts "

	python3 UAT1_UAT3_test.py && \
	python3 UAT2_P1_test.py && \
	python3 UAT2_P2_UAT4_test.py && \
	python3 UAT5_UAT6_test.py && \
	python3 UAT7_UAT8_test.py && \
	python3 UAT9_test.py && \
	python3 UAT10_test.py && \
	python3 UAT11_UAT12_UAT13_test.py && \
	python3 UAT14_test.py

