# Define the default target that runs when you just type 'make'.
all: run

# Define the rule for the 'run' target.
run:
	@echo "Running Python script..."
	python3 UAT1_UAT3_test.py
	python3 UAT2_P1_test.py
	python3 UAT2_P2_UAT4_test.py
	python3 UAT5_UAT6_test.py
	python3 UAT7_UAT8_test.py
	python3 UAT9_test.py
	python3 UAT10_test.py
	python3 UAT11_UAT12_UAT13_test.py
	python3 UAT14_test.py
