name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  client-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Client Dependencies
        run: npm install
      - name: Run Client Tests
        run: npm test

  server-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Server Dependencies
        run: npm install
      - name: Run Server Tests
        run: npm test
  
  Client-register-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium

      - name: Setup Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox-geckodriver

      - name: Run Selenium Test
        run: python3 selenium_test.py  
        #define automatice acceptance

  