name: CI/CD Pipeline

on:
  push:
    branches:
      - New_CI_CD
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - New_CI_CD

jobs:
  display-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Push Info
        run: |
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "Pusher Name: ${{ github.actor }}"
  
  Sprint-2-Scenario:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Start Server
      - name: Install Server Dependencies
        run: |
          cd server
          npm install
      - name: Start Server
        run: |
          cd server/src
          npm uninstall bcrypt
          npm install bcrypt
          node index.js &
        continue-on-error: true

      # Wait for Server to Start
      - name: Wait for Server to Start
        run: sleep 10

      # Start Client
      - name: Install Client Dependencies
        run: |
          cd client
          npm install
      - name: Start Client
        run: |
          cd client
          npm start &
        continue-on-error: true

      # Wait for Client to Start
      - name: Wait for Client to Start
        run: sleep 10

      - name: Setup Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          tar -xzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver

      # Run Selenium Tests
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Selenium dependencies
        run: pip install selenium

      - name: Test script
        run: |
          python3 Test/UAT1_UAT3_test.py
  

          
  Sprint-3-Scenario:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      # Start Server
      - name: Install Server Dependencies
        run: |
          cd server
          npm install
      - name: Start Server
        run: |
          cd server/src
          node index.js &
        continue-on-error: true
        
      # Wait for Server to Start
      - name: Wait for Server to Start
        run: sleep 10
        
      # Start Client
      - name: Install Client Dependencies
        run: |
          cd client
          npm install
      - name: Start Client
        run: |
          cd client
          npm start &
        continue-on-error: true
        
      # Wait for Client to Start
      - name: Wait for Client to Start
        run: sleep 10
        
      # Run Selenium Tests
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install Selenium dependencies
        run: pip install selenium
  
      - name: Setup Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
        
      - name: Test script
        run: |
          python3 Test/UAT1_UAT3_test.py
      

  #write a third job to that settup the chrome driver and run the selenium tests Test/UAT1_UAT3_test.py
  Test-Scenario:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Start Server
      - name: Install Server Dependencies
        run: |
          cd server
          npm install

      - name: Start Server
        run: |
          cd server/src
          node index.js &
        continue-on-error: true

      # Wait for Server to Start
      - name: Wait for Server to Start
        run: sleep 10

      # Start Client
      - name: Install Client Dependencies
        run: |
          cd client
          npm install

      - name: Start Client
        run: |
          cd client
          npm start &
        continue-on-error: true

      # Wait for Client to Start
      - name: Wait for Client to Start
        run: sleep 10

      # Run Selenium Tests
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Selenium dependencies
        run: pip install selenium

      - name: Setup Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Test script
        run: |
          python3 Test/UAT1_UAT3_test.py

  test-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      # Start Server
      - name: Install and Start Server
        run: |
          cd server
          npm install
          cd src
          npm uninstall bcrypt
          npm install bcrypt
          nohup node index.js &
        
      # Start Client
      - name: Install and Start Client
        run: |
          cd client
          npm install
          nohup npm start &
        
      - name: Wait for Applications to Start
        run: sleep 30
        
      # Setup Firefox
      - name: Setup Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          tar -xzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver
        
      # Run Selenium Tests
      - name: Set up Python and Run Selenium Tests
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install selenium
          python3 Test/UAT1_UAT3_test.py