name: CI/CD Pipeline

on:
  push:
    branches:
      - Ktesting
      - main
      - test
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - Ktesting
      - main
      - test

jobs:
  display-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Push Info
        run: |
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "Pusher Name: ${{ github.actor }}"
  
  Sprint-2-Scenario:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Start Server
      - name: Install Server Dependencies
        run: |
          cd server
          npm install
      - name: Start Server
        run: |
          cd server/src
          npm uninstall bcrypt
          npm install bcrypt
          node index.js &
        continue-on-error: true

      # Wait for Server to Start
      - name: Wait for Server to Start
        run: sleep 10

      # Start Client
      - name: Install Client Dependencies
        run: |
          cd client
          npm install
      - name: Start Client
        run: |
          cd client
          npm start &
        continue-on-error: true

      # Wait for Client to Start
      - name: Wait for Client to Start
        run: sleep 10

      - name: Setup Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # Run Selenium Tests
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Selenium dependencies
        run: pip install selenium

      - name: Register user Test
        run: |
          python3 Test/UAT1_UAT3_test.py
  
      - name: Login user Test
        run: |
          python3 Test/UAT2_P1_test.py
          python3 Test/UAT2_P2_UAT4_test.py
        
      - name: Check header consistansy and header menu
        run: |
          python3 Test/UAT5_UAT6_test.py
  
      - name: Check Basic search and visit request
        run: |
          python3 Test/UAT7_UAT8_test.py

          
  Sprint-3-Scenario:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      # Start Server
      - name: Install Server Dependencies
        run: |
          cd server
          npm install
      - name: Start Server
        run: |
          cd server/src
          node index.js &
        continue-on-error: true
        
      # Wait for Server to Start
      - name: Wait for Server to Start
        run: sleep 10
        
      # Start Client
      - name: Install Client Dependencies
        run: |
          cd client
          npm install
      - name: Start Client
        run: |
          cd client
          npm start &
        continue-on-error: true
        
      # Wait for Client to Start
      - name: Wait for Client to Start
        run: sleep 10
        
      # Run Selenium Tests
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install Selenium dependencies
        run: pip install selenium
  
      - name: Setup Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
        
      - name: Register user Test --
        run: |
          python3 Test/UAT1_UAT3_test.py
      
      - name: Search Broker test
        run: |
          python3 Test/UAT9_test.py

  test-Chromedriver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
             
      # Start Server
      - name: Install Server Dependencies
        run: |
          cd server
          npm install
      - name: Start Server
        run: |
          cd server/src
          node index.js &
        continue-on-error: true
        
      # Wait for Server to Start
      - name: Wait for Server to Start
        run: sleep 10
        
      # Start Client
      - name: Install Client Dependencies
        run: |
          cd client
          npm install
      - name: Start Client
        run: |
          cd client
          npm start &
        continue-on-error: true
        
      # Wait for Client to Start
      - name: Wait for Client to Start
        run: sleep 10
      

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
              
      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1)
          echo "Detected Chrome version: $CHROME_VERSION"
          CHROMEDRIVER_URL="https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION"
          CHROMEDRIVER_VERSION=$(curl -s "$CHROMEDRIVER_URL")
          if [[ "$CHROMEDRIVER_VERSION" == "" ]] || [[ "$CHROMEDRIVER_VERSION" == *"<Error>"* ]]; then
            echo "Failed to fetch the latest ChromeDriver version for Chrome version $CHROME_VERSION from $CHROMEDRIVER_URL"
            exit 1
          fi
          echo "Detected ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget -N "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -P ~/
          if [[ "$?" -ne 0 ]]; then
            echo "Failed to download ChromeDriver version $CHROMEDRIVER_VERSION"
            exit 1
          fi
          unzip ~/chromedriver_linux64.zip -d ~/
          rm -f ~/chromedriver_linux64.zip
          sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod 0755 /usr/local/bin/chromedriver
        
              
      # Install Selenium dependencies
      - name: Install Selenium dependencies
        run: pip install selenium
              
      # Run Selenium Test
      - name: Run UAT1_UAT3 Test
        run: python3 Test/UAT1_UAT3_test.py
          
              
        

