name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  display-push-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Push Info
        run: |
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "Pusher Name: ${{ github.actor }}"
