name: CI/CD Pipeline

on:
  push:
    branches:
      - Ktesting
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - Ktesting
  workflow_dispatch:

jobs:
  display-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Push Info
        run: |
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "Pusher Name: ${{ github.actor }}"

  Unit_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd client
          npm install
      - name: Run Unit Tests
        run: |
          cd client
          npm test  -- --coverage --no-cache
